//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class donation
    {
        public int id { get; set; }
        public decimal amount { get; set; }
        public int account_id { get; set; }
    
        public virtual north_shore_accounts north_shore_accounts { get; set; }
    }
}
