//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;
    
    public partial class image
    {
        public int id { get; set; }
        public int news_article_id { get; set; }
        public string img_src { get; set; }
        public int is_main { get; set; }
        public string caption { get; set; }
        public HttpPostedFileBase[] files { get; set; }
    
        public virtual news news { get; set; }
    }
}
