//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class news
    {
        public news()
        {
            this.images = new HashSet<image>();
        }
    
        public int id { get; set; }
        public string title { get; set; }
        public System.DateTime pub_date { get; set; }
        public string article_content { get; set; }
        public string article_summary { get; set; }
        public string author { get; set; }
    
        public virtual ICollection<image> images { get; set; }
    }
}
