//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class payment_information
    {
        public payment_information()
        {
            this.north_shore_accounts = new HashSet<north_shore_accounts>();
        }
    
        public int id { get; set; }
        public string credit_card { get; set; }
        public string ccv { get; set; }
        public System.DateTime exp_date { get; set; }
    
        public virtual ICollection<north_shore_accounts> north_shore_accounts { get; set; }
    }
}
